version: '3.8'

services:
  app:
    image: tjdgus3488/tave16-attendance:latest
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
    restart: always
    env_file:
      - /opt/app/.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  db_data: