spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

tave:
  key: ${JWT_SECRET_KEY}
  accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION}

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
  override-with-generic-response: false
